# Churn-Prediction using Neural Network

In [155]:
import pandas as pd
import numpy as np

In [156]:
df=pd.read_csv("C:\\Users\\user\\Datasets\\churn_modelling.csv")

In [157]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [158]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [159]:
df=df.drop(columns=['RowNumber','CustomerId','Surname'])

In [160]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [161]:
df.duplicated().sum()

0

In [162]:
df['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [163]:
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [164]:
df['Gender'].value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [165]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
df["Geography"]=lb.fit_transform(df['Geography'])
df["Gender"]=lb.fit_transform(df['Gender'])

In [166]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,0,0,42,2,0.00,1,1,1,101348.88,1
1,608,2,0,41,1,83807.86,1,0,1,112542.58,0
2,502,0,0,42,8,159660.80,3,1,0,113931.57,1
3,699,0,0,39,1,0.00,2,0,0,93826.63,0
4,850,2,0,43,2,125510.82,1,1,1,79084.10,0

In [167]:
x=df.drop(columns=['Exited'],axis=1)
y=df['Exited']

In [168]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [169]:
x_test.shape

(2000, 10)

In [170]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train_sc=sc.fit_transform(x_train)
x_test_sc=sc.fit_transform(x_test)

In [171]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [172]:
# ! pip install tensorflow

In [173]:
model=Sequential()

model.add(Dense(11,activation='relu',input_dim=10))
model.add(Dense(11,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

C:\Users\user\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [174]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_13 (Dense)                     │ (None, 11)                  │             121 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_14 (Dense)                     │ (None, 11)                  │             132 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_15 (Dense)                     │ (None, 1)                   │              12 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 265 (1.04 KB)

 Trainable params: 265 (1.04 KB)

 Non-trainable params: 0 (0.00 B)

In [175]:
model.compile(loss='binary_crossentropy',optimizer='Adam',metrics=['accuracy'])

In [176]:
history=model.fit(x_train_sc,y_train,epochs=100,validation_split=0.2)

Epoch 1/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6933 - loss: 0.6028 - val_accuracy: 0.7987 - val_loss: 0.4780
Epoch 2/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 972us/step - accuracy: 0.7971 - loss: 0.4665 - val_accuracy: 0.7987 - val_loss: 0.4502
Epoch 3/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 970us/step - accuracy: 0.7965 - loss: 0.4527 - val_accuracy: 0.8056 - val_loss: 0.4388
Epoch 4/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 975us/step - accuracy: 0.8091 - loss: 0.4373 - val_accuracy: 0.8156 - val_loss: 0.4313
Epoch 5/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 943us/step - accuracy: 0.8154 - loss: 0.4264 - val_accuracy: 0.8188 - val_loss: 0.4252
Epoch 6/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 922us/step - accuracy: 0.8121 - loss: 0.4440 - val_accuracy: 0.8256 - val_loss: 0.4194
Epoch 7/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 957us/step - accuracy: 0.8173 - loss: 0.4282 - val_accuracy: 0.8281 - val_loss: 0.4133
Epoch 8/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 949us/step - accuracy: 0.8265 - loss: 0.4143 - val_accuracy: 0.8306 - val_loss: 0.4080
Epoch 9/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 970us/step - accuracy: 0.8226 - loss: 0.4153 - val_accuracy: 0.8344 - val_loss: 0.4031
Epoch 10/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8297 - loss: 0.4083 - val_accuracy: 0.8381 - val_loss: 0.3971
Epoch 11/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8392 - loss: 0.3961 - val_accuracy: 0.8444 - val_loss: 0.3899
Epoch 12/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 970us/step - accuracy: 0.8369 - loss: 0.3961 - val_accuracy: 0.8500 - val_loss: 0.3803
Epoch 13/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 976us/step - accuracy: 0.8411 - loss: 0.3836 - val_accuracy: 0.8481 - val_loss: 0.3722
Epoch 14/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 972us/step - accuracy: 0.8551 - loss: 0.3596 - val_accuracy: 0.8512 - val_loss: 0.3647
Epoch 15/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 987us/step - accuracy: 0.8592 - loss: 0.3545 - val_accuracy: 0.8569 - val_loss: 0.3600
Epoch 16/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 979us/step - accuracy: 0.8494 - loss: 0.3617 - val_accuracy: 0.8550 - val_loss: 0.3558
Epoch 17/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 970us/step - accuracy: 0.8655 - loss: 0.3410 - val_accuracy: 0.8537 - val_loss: 0.3533
Epoch 18/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8558 - loss: 0.3539 - val_accuracy: 0.8531 - val_loss: 0.3521
Epoch 19/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 967us/step - accuracy: 0.8627 - loss: 0.3393 - val_accuracy: 0.8512 - val_loss: 0.3517
Epoch 20/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 957us/step - accuracy: 0.8589 - loss: 0.3359 - val_accuracy: 0.8537 - val_loss: 0.3494
Epoch 21/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8653 - loss: 0.3289 - val_accuracy: 0.8512 - val_loss: 0.3493
Epoch 22/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8539 - loss: 0.3441 - val_accuracy: 0.8544 - val_loss: 0.3485
Epoch 23/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 968us/step - accuracy: 0.8611 - loss: 0.3357 - val_accuracy: 0.8519 - val_loss: 0.3479
Epoch 24/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 962us/step - accuracy: 0.8569 - loss: 0.3454 - val_accuracy: 0.8550 - val_loss: 0.3476
Epoch 25/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 999us/step - accuracy: 0.8582 - loss: 0.3458 - val_accuracy: 0.8550 - val_loss: 0.3475
Epoch 26/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 967us/step - accuracy: 0.8585 - loss: 0.3443 - val_accuracy: 0.8569 - val_loss: 0.3475
Epoch 27/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 964us/step - accuracy: 0.8680 - loss: 0.3342 - val_accuracy: 0.8519 - val_loss: 0.3477
Epoch 28/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 956us/step - accuracy: 0.8641 - loss: 0.3277 - val_accuracy: 0.8512 - val_loss: 0.3466
Epoch 29/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8597 - loss: 0.3364 - val_accuracy: 0.8544 - val_loss: 0.3468
Epoch 30/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8681 - loss: 0.3340 - val_accuracy: 0.8544 - val_loss: 0.3476
Epoch 31/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 979us/step - accuracy: 0.8619 - loss: 0.3373 - val_accuracy: 0.8519 - val_loss: 0.3468
Epoch 32/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 954us/step - accuracy: 0.8718 - loss: 0.3188 - val_accuracy: 0.8525 - val_loss: 0.3471
Epoch 33/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 969us/step - accuracy: 0.8680 - loss: 0.3346 - val_accuracy: 0.8525 - val_loss: 0.3480
Epoch 34/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 966us/step - accuracy: 0.8686 - loss: 0.3232 - val_accuracy: 0.8500 - val_loss: 0.3464
Epoch 35/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8614 - loss: 0.3367 - val_accuracy: 0.8569 - val_loss: 0.3475
Epoch 36/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 963us/step - accuracy: 0.8663 - loss: 0.3289 - val_accuracy: 0.8487 - val_loss: 0.3472
Epoch 37/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 950us/step - accuracy: 0.8648 - loss: 0.3379 - val_accuracy: 0.8494 - val_loss: 0.3476
Epoch 38/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 956us/step - accuracy: 0.8684 - loss: 0.3306 - val_accuracy: 0.8544 - val_loss: 0.3471
Epoch 39/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 937us/step - accuracy: 0.8695 - loss: 0.3210 - val_accuracy: 0.8531 - val_loss: 0.3475
Epoch 40/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 944us/step - accuracy: 0.8664 - loss: 0.3304 - val_accuracy: 0.8487 - val_loss: 0.3473
Epoch 41/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8683 - loss: 0.3275 - val_accuracy: 0.8544 - val_loss: 0.3475
Epoch 42/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 969us/step - accuracy: 0.8607 - loss: 0.3406 - val_accuracy: 0.8506 - val_loss: 0.3468
Epoch 43/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 993us/step - accuracy: 0.8640 - loss: 0.3262 - val_accuracy: 0.8544 - val_loss: 0.3483
Epoch 44/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 979us/step - accuracy: 0.8662 - loss: 0.3309 - val_accuracy: 0.8525 - val_loss: 0.3482
Epoch 45/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 987us/step - accuracy: 0.8649 - loss: 0.3311 - val_accuracy: 0.8544 - val_loss: 0.3486
Epoch 46/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8607 - loss: 0.3417 - val_accuracy: 0.8544 - val_loss: 0.3473
Epoch 47/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 946us/step - accuracy: 0.8722 - loss: 0.3188 - val_accuracy: 0.8506 - val_loss: 0.3473
Epoch 48/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 941us/step - accuracy: 0.8663 - loss: 0.3357 - val_accuracy: 0.8512 - val_loss: 0.3472
Epoch 49/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 965us/step - accuracy: 0.8705 - loss: 0.3221 - val_accuracy: 0.8469 - val_loss: 0.3476
Epoch 50/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 972us/step - accuracy: 0.8644 - loss: 0.3223 - val_accuracy: 0.8512 - val_loss: 0.3479
Epoch 51/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8556 - loss: 0.3523 - val_accuracy: 0.8519 - val_loss: 0.3489
Epoch 52/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8649 - loss: 0.3300 - val_accuracy: 0.8562 - val_loss: 0.3475
Epoch 53/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8636 - loss: 0.3289 - val_accuracy: 0.8506 - val_loss: 0.3481
Epoch 54/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8695 - loss: 0.3196 - val_accuracy: 0.8531 - val_loss: 0.3480
Epoch 55/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 997us/step - accuracy: 0.8639 - loss: 0.3259 - val_accuracy: 0.8525 - val_loss: 0.3471
Epoch 56/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8665 - loss: 0.3295 - val_accuracy: 0.8519 - val_loss: 0.3476
Epoch 57/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 975us/step - accuracy: 0.8654 - loss: 0.3274 - val_accuracy: 0.8500 - val_loss: 0.3482
Epoch 58/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8610 - loss: 0.3316 - val_accuracy: 0.8506 - val_loss: 0.3481
Epoch 59/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 978us/step - accuracy: 0.8708 - loss: 0.3220 - val_accuracy: 0.8519 - val_loss: 0.3482
Epoch 60/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 995us/step - accuracy: 0.8636 - loss: 0.3288 - val_accuracy: 0.8525 - val_loss: 0.3499
Epoch 61/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8567 - loss: 0.3361 - val_accuracy: 0.8537 - val_loss: 0.3475
Epoch 62/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8672 - loss: 0.3210 - val_accuracy: 0.8531 - val_loss: 0.3487
Epoch 63/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8654 - loss: 0.3291 - val_accuracy: 0.8506 - val_loss: 0.3497
Epoch 64/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8713 - loss: 0.3250 - val_accuracy: 0.8525 - val_loss: 0.3488
Epoch 65/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8689 - loss: 0.3239 - val_accuracy: 0.8525 - val_loss: 0.3488
Epoch 66/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 975us/step - accuracy: 0.8667 - loss: 0.3288 - val_accuracy: 0.8512 - val_loss: 0.3507
Epoch 67/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8728 - loss: 0.3200 - val_accuracy: 0.8537 - val_loss: 0.3495
Epoch 68/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8697 - loss: 0.3198 - val_accuracy: 0.8512 - val_loss: 0.3480
Epoch 69/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 979us/step - accuracy: 0.8697 - loss: 0.3183 - val_accuracy: 0.8494 - val_loss: 0.3505
Epoch 70/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 957us/step - accuracy: 0.8690 - loss: 0.3251 - val_accuracy: 0.8531 - val_loss: 0.3495
Epoch 71/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 949us/step - accuracy: 0.8666 - loss: 0.3235 - val_accuracy: 0.8525 - val_loss: 0.3481
Epoch 72/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8672 - loss: 0.3238 - val_accuracy: 0.8531 - val_loss: 0.3486
Epoch 73/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 945us/step - accuracy: 0.8641 - loss: 0.3235 - val_accuracy: 0.8525 - val_loss: 0.3491
Epoch 74/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 942us/step - accuracy: 0.8612 - loss: 0.3317 - val_accuracy: 0.8562 - val_loss: 0.3482
Epoch 75/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8665 - loss: 0.3235 - val_accuracy: 0.8556 - val_loss: 0.3483
Epoch 76/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 982us/step - accuracy: 0.8690 - loss: 0.3231 - val_accuracy: 0.8544 - val_loss: 0.3494
Epoch 77/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 978us/step - accuracy: 0.8659 - loss: 0.3220 - val_accuracy: 0.8519 - val_loss: 0.3496
Epoch 78/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8745 - loss: 0.3107 - val_accuracy: 0.8500 - val_loss: 0.3507
Epoch 79/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 988us/step - accuracy: 0.8674 - loss: 0.3221 - val_accuracy: 0.8537 - val_loss: 0.3489
Epoch 80/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8675 - loss: 0.3277 - val_accuracy: 0.8544 - val_loss: 0.3498
Epoch 81/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 966us/step - accuracy: 0.8659 - loss: 0.3272 - val_accuracy: 0.8537 - val_loss: 0.3485
Epoch 82/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 971us/step - accuracy: 0.8712 - loss: 0.3273 - val_accuracy: 0.8556 - val_loss: 0.3487
Epoch 83/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 930us/step - accuracy: 0.8615 - loss: 0.3294 - val_accuracy: 0.8537 - val_loss: 0.3492
Epoch 84/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8669 - loss: 0.3203 - val_accuracy: 0.8525 - val_loss: 0.3506
Epoch 85/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 969us/step - accuracy: 0.8674 - loss: 0.3306 - val_accuracy: 0.8544 - val_loss: 0.3487
Epoch 86/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8662 - loss: 0.3220 - val_accuracy: 0.8562 - val_loss: 0.3495
Epoch 87/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 967us/step - accuracy: 0.8683 - loss: 0.3225 - val_accuracy: 0.8537 - val_loss: 0.3512
Epoch 88/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 980us/step - accuracy: 0.8712 - loss: 0.3209 - val_accuracy: 0.8556 - val_loss: 0.3501
Epoch 89/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8650 - loss: 0.3274 - val_accuracy: 0.8531 - val_loss: 0.3511
Epoch 90/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 991us/step - accuracy: 0.8669 - loss: 0.3262 - val_accuracy: 0.8531 - val_loss: 0.3527
Epoch 91/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8642 - loss: 0.3300 - val_accuracy: 0.8531 - val_loss: 0.3495
Epoch 92/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8644 - loss: 0.3200 - val_accuracy: 0.8512 - val_loss: 0.3493
Epoch 93/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 957us/step - accuracy: 0.8698 - loss: 0.3218 - val_accuracy: 0.8575 - val_loss: 0.3501
Epoch 94/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8616 - loss: 0.3319 - val_accuracy: 0.8519 - val_loss: 0.3523
Epoch 95/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 965us/step - accuracy: 0.8688 - loss: 0.3208 - val_accuracy: 0.8544 - val_loss: 0.3507
Epoch 96/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 984us/step - accuracy: 0.8760 - loss: 0.3059 - val_accuracy: 0.8525 - val_loss: 0.3517
Epoch 97/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8624 - loss: 0.3287 - val_accuracy: 0.8556 - val_loss: 0.3496
Epoch 98/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 992us/step - accuracy: 0.8590 - loss: 0.3364 - val_accuracy: 0.8575 - val_loss: 0.3511
Epoch 99/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8672 - loss: 0.3195 - val_accuracy: 0.8556 - val_loss: 0.3493
Epoch 100/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 975us/step - accuracy: 0.8718 - loss: 0.3114 - val_accuracy: 0.8575 - val_loss: 0.3499

In [177]:
model.layers[0].get_weights()

[array([[ 0.00595341,  0.14906552,  0.2709263 , -0.01814365,  0.07778041,
          0.05956233,  0.17347687, -0.1533808 , -0.09128218, -0.19322398,
         -0.04560099],
        [ 0.6330399 , -0.9618345 , -0.12077483,  0.32235378,  0.09189834,
         -0.00285393, -0.46353114, -0.6219648 ,  0.17019741,  0.5715581 ,
          0.7779176 ],
        [ 0.47586778,  0.11033868, -0.32206702, -0.15645917,  0.02269747,
          0.00802973,  0.52725184, -0.04477607, -0.02525763,  0.10551488,
         -0.10876807],
        [-0.9695436 ,  0.19477348, -0.3742384 , -0.05331055,  0.7231108 ,
         -0.7727602 ,  0.08991291, -0.38615906,  0.6678812 , -0.21630414,
          0.66285765],
        [-0.07792949, -0.05189135, -0.20242316,  0.20106412, -0.3742096 ,
          0.00494641,  0.33161443,  0.16764913, -0.19796076,  0.789342  ,
          0.10977724],
        [ 0.41979662,  0.22215697, -0.716246  , -0.02209522,  0.03801738,
         -0.06925723, -0.835759  ,  0.0427946 , -0.00806043, -0.45131963,
         -0.01778446],
        [ 0.05110691,  0.863485  , -0.46911126,  1.067457  , -0.46365497,
          0.13936801, -0.5411594 ,  0.083097  , -0.09974128, -0.01397772,
          0.38098648],
        [-0.2016319 ,  0.19659986,  0.1503609 , -0.07716769, -0.22001435,
         -0.04328498, -0.18327716, -0.07442565,  0.13701716, -0.15278523,
          0.07132844],
        [ 0.03109308,  0.63996404, -0.29725477, -0.23329775, -0.29922873,
         -0.35543746,  0.36707506, -0.19993548,  1.2947168 , -0.2182591 ,
          0.15563655],
        [ 0.30379352,  0.12474189, -0.01986221, -0.13551481,  0.31047466,
          0.00207107, -0.13533029, -0.28115833,  0.09352018, -0.44796205,
         -0.14086209]], dtype=float32),
 array([-0.05522545,  0.26683572,  0.33232474, -0.38782424, -0.06398322,
         1.080181  ,  0.26243702,  0.10290527,  0.00216259,  0.9889249 ,
        -0.13811491], dtype=float32)]

In [178]:
y_log=model.predict(x_test_sc)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

In [179]:
y_pred=np.where(y_log>0.5,1,0)

In [180]:
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_test,y_pred)

In [181]:
print(accuracy)

0.863

In [184]:
# import matplotlib.pyplot as plt
# plt.plot(history.history['loss'])
# plt.plot(history.history['val_loss'])

In [185]:
# plt.plot(history.history['accuracy'])
# plt.plot(history.history['val_accuracy'])